### ISSUE TITLE
Shine.SaveJSONFile is not writing the file for shuffle happiness, causing users at high elo to rarely ever get their choice of team

### ISSUE THREAD

**Issue by nightmarens2** [Person8880/Shine#886]
```
function BalanceModule:SaveHappinessHistory()
	Shine.SaveJSONFile( self.HappinessHistory, self.HappinessHistoryFile )
end
```
This function does not write the file. Last known good save of that file was on September 1 of 2021. I've verified permissions on the directory and the file for the user running the server and those are fine. I've renamed the file and it did not create a new one and none of the servers I have (12 of them) are writing to the file. 

this function in 

./lua/shine/core/shared/config.lua
```
local JSONErrorHandler = Shine.BuildErrorHandler( "JSON serialisation error" )
function Shine.SaveJSONFile( Table, Path, Settings )
	Settings = Settings or JSONSettings

	local FormattingOptions = {
		PrettyPrint = Settings.indent or false,
		IndentSize = 4 * ( Settings.level or 1 )
	}
	if not FormattingOptions.PrettyPrint then
		-- No point having consistent order if not pretty printing.
		FormattingOptions.TableIterator = pairs
	end

	local Success, JSON = xpcall( TableToJSON, JSONErrorHandler, Table, FormattingOptions )
	if not Success then
		-- Fallback to DKJSON if there's somehow a bug in our serialiser.
		JSON = Encode( Table, Settings )
	end

	return WriteFile( Path, JSON )
end
```
I just turned on debug on the basecommands.json file so start next round it might show, I haven't traced back the source code to know if this will include things like this to print to log:
`local JSONErrorHandler = Shine.BuildErrorHandler( "JSON serialisation error" )
`

**Comment by nightmarens2** [comment]
Ok, so we figured it out. We printed debug messages along the way:
turns out it boils down to this:

```
--[[
	Can only apply this optimisation if we are using a single skill value.
	If a player has a different skill depending on which team they are on/if they are a commander, swapping will have
	dire consequences.

	Also, commanders must not be swapped if configured to ignore them, so there also must be no commanders present in
	the teams if ignoring is enabled.
]]
function BalanceModule:ShouldOptimiseHappiness( TeamMembers )
	return not self:IsPerTeamSkillEnabled() and not (
		( self.Config.IgnoreCommanders or self:IsCommanderSkillEnabled() ) and
		TeamMembersContainCommander( TeamMembers )
	)
end
```

therefore, if the game starts with no commanders, or if the commander skill is used for shuffle, or team skill, then it won't do optimization. The issue with this is that every ranked game should shuffle based off of commanders, but the distribution of player skills when including extremely high skilled players (compared to the average) means that they are almost exclusively forced to play on one team or another, regardless of their choices. 

the optimization written here:
```
function BalanceModule:GetHistoricHappinessWeightForClient( Client )
	local RoundHistory = self.HappinessHistory
	local Weight = 1
	local SteamID = tostring( Client:GetUserId() )

	for i = 1, #RoundHistory do
		local Round = RoundHistory[ i ]
		local WasHappy = Round[ SteamID ]
		if WasHappy ~= nil then
			-- For every round they got the team they wanted, halve their weighting.
			-- For every round they did not get the team they wanted, double their weighting.
			-- This means that players that consistently get what they want will be less able to offset
			-- unhappy players, and those that consistently do not get what they want will quickly grow
			-- to have a far larger weighting than anyone else.
			Weight = Weight * ( WasHappy and 0.5 or 2 )
			self.Logger:Trace( "%s was %s in round %d, making their weight %s",
				SteamID, WasHappy and "happy" or "not happy", i, Weight )
		end
	end

	return Weight
end
```
Is powerful and would resolve this issue, but the optimise happiness functionality needs to be rewritten so that it will not move commanders, but still allows for the commander skill to be accounted for in the shuffle and for the game to be started with commanders. 

The lack of the happiness optimisation is having a massive effect on a certain percentage of players and there are virtually no scenarios where a game would start without commanders, commander hive skill would be disabled or per team skill is disabled, making one of the most powerful features of the shuffle completely unused. 


Please make happiness optimization happen when:

- the game starts with commanders
- commander hive skill is included in shuffle algorithm
- per team hive skill is included

**Comment by Person8880** [comment]
The team swapping optimisation isn't feasible to use when there's per team skill. Swapping players would result in drastically different skills, as noted by the comment.

The real problem here is an oversight in the recording of the happiness history. It should be recording it as it's [used as a weighting](https://github.com/Person8880/Shine/blob/develop/lua/shine/extensions/voterandom/team_balance.lua#L673) multiplier for team preference, but due to the check that precludes swapping the teams, the team preferences are never recorded. This would explain a bunch of historic complaints, and I'm figuratively kicking myself for not spotting it before.

I don't have time to work on this right now, but I'll try to get it fixed at the weekend.

**Comment by nightmarens2** [comment]
@Person8880  

I see your unit test:
```

VoteShuffle.Config.IgnoreCommanders = false
VoteShuffle.Config.BalanceModeConfig[ VoteShuffle.ShuffleMode.HIVE ].UseTeamSkill = false
VoteShuffle.Config.BalanceModeConfig[ VoteShuffle.ShuffleMode.HIVE ].UseCommanderSkill = false
```

The only thing here is that there is no reason on the server side to ever run the options you have here in your unit test, therefore we still have the issue of happiness not being accounted for as the users simply will never be in a scenario where the new logic you wrote actually is used. If we were to ignore commander skill, for example, players could just have a low field skill and rack their commander skill up extremely high, and every shuffle would be favoring these players because their impact on the game is never accounted for and therefore the more they win like that, the more imbalanced the game becomes in their favor. 

If I had 600 field skill, but 3900 commander skill, the shuffle would use my 600 field skill to balance the teams, and i'd continue to win as commander with no counter balance, while with commander skill enabled, the higher the commander skill is, the harder it it is to win. 

The field skill barely goes up if at all when commanding, unless you jump out of the chair here and there and even then it hardly goes up. 

The real solution we need is to have happiness working when the following conditions are true:
```
VoteShuffle.Config.BalanceModeConfig[ VoteShuffle.ShuffleMode.HIVE ].UseTeamSkill = true
VoteShuffle.Config.BalanceModeConfig[ VoteShuffle.ShuffleMode.HIVE ].UseCommanderSkill = true
```

**Comment by Person8880** [comment]
Those test parameters aren't particularly important, they just make the mocked logic easier. There's no real distinction between mocking skills and mocking team skills, the tests are only asserting over the results based on the numbers provided, which is all the optimisation process actually cares about. There is a test case to cover per-team skills, but it's mostly just checking that team parameters are being passed along and used.

As I mentioned in my previous comment, the happiness weighting is applied during the optimisation process as part of the cost function. Thus, now that the history is being recorded properly, previous team assignments should affect the end results. How much it affects the results depends on a given player's place in the server's skill distribution, and how even that distribution is.

It's not feasible to perform the entire team swap for the reasons I mentioned before. Skills are asymmetric, what may be balanced in one configuration could blow up when swapped.

For example, skills could go from this:

|Marines|Aliens|
|------------|--------|
|3000|3000|
|2000|2000|
|1500|1250|
|1000|1250|
|500|500|

to this:

|Marines|Aliens|
|------------|---------|
|4000|2000|
|4000|2000|
|2000|1500|
|1000|1500|
|500|500|

and the only way to fix it would be to run the optimiser again, at which point there's no guarantee anyone would be on the team they wanted and it would likely just end up back to where it started.

**Comment by nightmarens2** [comment]
Ok, so to confirm, using these values, the happiness optimization should factor into the cost weighting now?

```
    "BalanceModeConfig": {
        "HIVE": {
            "BlendAlienCommanderAndFieldSkills": false,
            "UseCommanderSkill": true,
            "UseTeamSkill": true
        }
    },
```

**Comment by nightmarens2** [comment]
I see what you're saying in the previous comment, because the happiness was never stored due to the check that precluded it, it simply never recorded, therefore didn't work, now that it is recording, it still goes into the cost weighting, regardless of the settings I noted in the previous comment, though some challenges arise from trying to swap players in larger groups or "whole team" due to the asymmetry of the duality of per team skills, therefore some of the behavior that would have happened prior to per team skill is simply not possible now, therefore the way it statistically distributes possible outcomes is a bit different.
